version: "2"
run:
  concurrency: 16
  go: "1.24"
  modules-download-mode: mod
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - decorder
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - .*_gen\.go$
      - .*setup\.go$
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports
    - gci
    - golines
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/CodeLieutenant/uberfx-common/v3
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/CodeLieutenant/uberfx-common/v3)
      no-inline-comments: true
    golines:
      max-len: 180
      shorten-comments: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
