version: '3'

tasks:
  fmt:
    cmds:
      - go tool golangci-lint fmt
  lint:
    cmds:
      - go tool golangci-lint run --color "always"
  sec:
    cmds:
      - go tool gosec ./...
  tidy:
    cmds:
      - rm -f go.sum
      - go mod tidy
  update:
    cmds:
      - go get -u ./... # Updates regular packages
      - go get -u -t ./... # Updates Test packages
  fieldalign:
    cmds:
      - go tool fieldalignment -fix ./...
  test:
    cmds:
      - go test -covermode=atomic -race -coverprofile=coverage.txt -timeout 5m -json -v ./... | go tool gotestfmt -showteststatus
